### ISSUE TITLE
Cannot find module 'jshint/src/cli'

### ISSUE THREAD

**Issue by yinzSE** [amazeui/starter-kit#7]
```
$ gulp serve
[17:29:57] Using gulpfile ~/starter-kit/gulpfile.js
[17:29:57] Starting 'default'...
[17:29:57] Starting 'clean'...
[17:29:57] Finished 'clean' after 8.88 ms
[17:29:57] Starting 'styles'...
[17:29:57] Starting 'jshint'...
[17:29:57] 'jshint' errored after 7.32 ms
[17:29:57] Error: Cannot find module 'jshint/src/cli'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/yinz/starter-kit/node_modules/gulp-jshint/src/extract.js:1:79)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
[17:29:57] 'default' errored after 138 ms
[17:29:57] Error in plugin 'run-sequence'
Message:
    An error occured in task 'jshint'.
[17:29:58] styles all files 910 B
[17:29:58] Finished 'styles' after 328 ms

$ node -v
v5.7.1
$ npm -v
3.6.0
```

**Comment by yinzSE** [comment]
需要手动安装 `jshint`
package.json 里没写相关依赖,  `gulp-jshint` 也没有自动安装相关依赖
 是 NPM3 的问题 ?

**Comment by minwe** [comment]
应该是 NPM 3 的问题

https://github.com/spalger/gulp-jshint/blob/d7cc9ea0424abcbcbba3ef18b92e5e9560bd4286/package.json#L22-L24

gulp-jshint 把 jshint 写在 `peerDependencies` 里了，NPM 3 不会自动安装 `peerDependencies`。

目前建议使用 NPM 2，很多模块还没有做兼容 NPM 3 的调整。
